"use client";
import "./styles/globals.css";
import { Lexend } from "next/font/google";

const lexend = Lexend({ subsets: ["latin"], weight: "400" });

// COMPLETED
export const metadata = {
  title: "Huge Bites",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" class="dark">
      <title>Huge Bites</title>

      <body className={lexend.className}>{children}</body>
    </html>
  );
}
