"use client";
import "./styles/globals.css";
import { Lexend } from "next/font/google";

const lexend = Lexend({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Huge Bites",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>Huge Bites</title>

      <body className={lexend.className}>{children}</body>
    </html>
  );
}

// const [loggedInUserName, setLoggedInUserName] = useState("");
// const [loggedInUserId, setLoggedInUserId] = useState("");

// useEffect(() => {
//   const userId =
//     typeof window !== "undefined" && window.localStorage
//       ? localStorage.getItem("accountId")
//       : "";
//   const userName =
//     typeof window !== "undefined" && window.localStorage
//       ? localStorage.getItem("userName")
//       : "";

//   {
//     userId && setLoggedInUserId(userId);
//   }

//   {
//     userName && setLoggedInUserName(userName);
//   }
// }, []);
